# content of service-account-credentials.json, used to access to Google Cloud Platform
gcp_credentials: ENCRYPTED[0006392fac64aa1d1fa874595c4ec576060fde31e860d8b1f4c2e015bc44522c46638ba15e73356d76867e06b320cdf7]

#
# ENV VARIABLES
#
env:
  ### Shared variables
  ARTIFACTORY_URL: ENCRYPTED[!2f8fa307d3289faa0aa6791f18b961627ae44f1ef46b136e1a1e63b0b4c86454dbb25520d49b339e2d50a1e1e5f95c88!]
  ARTIFACTORY_PRIVATE_USERNAME: repox-private-reader-e2882e
  ARTIFACTORY_PRIVATE_PASSWORD: ENCRYPTED[!815fc7526a6579b7d974d1c41b5c247cfed8c88fb2c7b41ec5d3d54244701186da777c4003476b5b9fa208c8b8f208dc!]
  ARTIFACTORY_API_KEY: ENCRYPTED[!815fc7526a6579b7d974d1c41b5c247cfed8c88fb2c7b41ec5d3d54244701186da777c4003476b5b9fa208c8b8f208dc!]
  ARTIFACTORY_DEPLOY_USERNAME: repox-qa-deployer
  ARTIFACTORY_DEPLOY_PASSWORD: ENCRYPTED[!d484e19f33c9ce63b165f70e414a33b1ac6c215a126791aacbf8059626caf0fd8a78e999a20af5c1a4ba01c0b0247921!]
  ARTIFACTORY_DEPLOY_REPO: sonarsource-public-qa

  GCF_ACCESS_TOKEN: ENCRYPTED[!1fb91961a5c01e06e38834e55755231d649dc62eca354593105af9f9d643d701ae4539ab6a8021278b8d9348ae2ce8be!]
  PROMOTE_URL: ENCRYPTED[!e22ed2e34a8f7a1aea5cff653585429bbd3d5151e7201022140218f9c5d620069ec2388f14f83971e3fd726215bc0f5e!]

  GITHUB_TOKEN: ENCRYPTED[!f458126aa9ed2ac526f220c5acb51dd9cc255726b34761a56fc78d4294c11089502a882888cef0ca7dd4085e72e611a5!]

  BURGR_URL: ENCRYPTED[!c7e294da94762d7bac144abef6310c5db300c95979daed4454ca977776bfd5edeb557e1237e3aa8ed722336243af2d78!]
  BURGR_USERNAME: ENCRYPTED[!b29ddc7610116de511e74bec9a93ad9b8a20ac217a0852e94a96d0066e6e822b95e7bc1fe152afb707f16b70605fddd3!]
  BURGR_PASSWORD: ENCRYPTED[!83e130718e92b8c9de7c5226355f730e55fb46e45869149a9223e724bb99656878ef9684c5f8cfef434aa716e87f4cf2!]

  ### Project variables
  DEPLOY_PULL_REQUEST: true
  ARTIFACTS: org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:jar,org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:json:cyclonedx

  ORG_GRADLE_PROJECT_signingKey: ENCRYPTED[!cc216dfe592f79db8006f2a591f8f98b40aa2b078e92025623594976fd32f6864c1e6b6ba74b50647f608e2418e6c336!]
  ORG_GRADLE_PROJECT_signingPassword: ENCRYPTED[!314a8fc344f45e462dd5e8dccd741d7562283a825e78ebca27d4ae9db8e65ce618e7f6aece386b2782a5abe5171467bd!]
  ORG_GRADLE_PROJECT_signingKeyId: 0x7DCD4258

  CIRRUS_SHELL: bash

#
# RE-USABLE CONFIGS
#
container_definition: &CONTAINER_DEFINITION
  dockerfile: integrationTests/docker/Dockerfile
  builder_image_project: sonarqube-team
  builder_image_name: docker-builder-v20200915
  cluster_name: cirrus-ci-cluster
  zone: us-central1-a
  namespace: default

container_definition_11: &CONTAINER_DEFINITION_11
  dockerfile: integrationTests/docker/Dockerfile_java11
  builder_image_project: sonarqube-team
  builder_image_name: docker-builder-v20200915
  cluster_name: cirrus-ci-cluster
  zone: us-central1-a
  namespace: default

container_definition_17: &CONTAINER_DEFINITION_17
  dockerfile: integrationTests/docker/Dockerfile_java17
  builder_image_project: sonarqube-team
  builder_image_name: docker-builder-v20200915
  cluster_name: cirrus-ci-cluster
  zone: us-central1-a
  namespace: default

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*")

build_task:
  gke_container:
    <<: *CONTAINER_DEFINITION_11
    cpu: 1.5
    memory: 4G
  env:
    SONAR_TOKEN: ENCRYPTED[!b6fd814826c51e64ee61b0b6f3ae621551f6413383f7170f73580e2e141ac78c4b134b506f6288c74faa0dd564c05a29!]
    SONAR_HOST_URL: https://next.sonarqube.com/sonarqube
  gradle_cache:
    folder: ~/.gradle/caches
  script:
    - source cirrus-env BUILD
    - regular_gradle_build_deploy_analyze
  on_failure:
    reports_artifacts:
      path: "**/build/reports/**/*"
    junit_artifacts:
      path: "**/test-results/**/*.xml"
      format: junit

gradle_qa_java8_task:
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  gke_container:
    <<: *CONTAINER_DEFINITION
    cpu: 2
    memory: 2G
  env:
    matrix:
      - GRADLE_VERSION: 6.8.3
        ANDROID_GRADLE_VERSION: 4.2.0
      - GRADLE_VERSION: 5.6.4
        ANDROID_GRADLE_VERSION: 3.3.2
      - GRADLE_VERSION: 4.6
        ANDROID_GRADLE_VERSION: 3.2.1
  gradle_cache:
    folder: ~/.gradle/caches
  script:
    - ./cirrus/cirrus-qa.sh
  cleanup_before_cache_script:
    - ./cirrus/cleanup-gradle-cache.sh

gradle_qa_java11_task:
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  gke_container:
    <<: *CONTAINER_DEFINITION_11
    cpu: 2
    memory: 2G
  env:
    matrix:
      - GRADLE_VERSION: 7.4.1
        ANDROID_GRADLE_VERSION: 7.1.0
      - GRADLE_VERSION: 6.8.3
        ANDROID_GRADLE_VERSION: 4.2.0
  gradle_cache:
    folder: ~/.gradle/caches
  script:
    - ./cirrus/cirrus-qa.sh
  cleanup_before_cache_script:
    - ./cirrus/cleanup-gradle-cache.sh

gradle_qa_java17_task:
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  gke_container:
    <<: *CONTAINER_DEFINITION_17
    cpu: 2
    memory: 2G
  env:
    matrix:
      - GRADLE_VERSION: 7.4.1
        ANDROID_GRADLE_VERSION: 7.1.0
  gradle_cache:
    folder: ~/.gradle/caches
  script:
    - ./cirrus/cirrus-qa.sh
  cleanup_before_cache_script:
    - ./cirrus/cleanup-gradle-cache.sh

promote_task:
  depends_on:
    - build
    - gradle_qa_java8
    - gradle_qa_java11
    - gradle_qa_java17
  <<: *ONLY_SONARSOURCE_QA
  gke_container:
    <<: *CONTAINER_DEFINITION
    cpu: 0.5
    memory: 500M
  script:
    - source cirrus-env PROMOTE
    - curl -sfSL -H "Authorization: Bearer $GCF_ACCESS_TOKEN" "$PROMOTE_URL/$GITHUB_REPO/$GITHUB_BRANCH/$BUILD_NUMBER/$PULL_REQUEST?multi=true"
    - burgr-notify-promotion

release_to_plugin_portal_task:
  only_if: $CIRRUS_PRERELEASE != "true" && $CIRRUS_RELEASE != ""
  stateful: 'true'
  depends_on:
    - promote
  gke_container:
    <<: *CONTAINER_DEFINITION_11
    cpu: 1.5
    memory: 4G
  gradle_cache:
    folder: ~/.gradle/caches
  env:
    GRADLE_PUBLISH_KEY: ENCRYPTED[03bb20fd7f88b6d97cde0bdfd8999a34804eaa7394b6da397712823088ba07fd0bcc8093f85c719414e8f43bc5ed6f0a]
    GRADLE_PUBLISH_SECRET: ENCRYPTED[91e21822690cfd6bf4e5a7653f79545e0ce8501759cb36643e77f8e35156388f27b3c57f03e9e8b8126df7679feeee5f]
    JFROG_PROMOTER: ENCRYPTED[aa431a946fd2e021aca3991bf8e91e55c188443cfd323673d28b8bfbb41e9c5b33b873d520400edfeab2e77835057054]
  script:
    - source cirrus-env RELEASE
    - gradle --info --stacktrace --console plain "-Pgradle.publish.key=${GRADLE_PUBLISH_KEY}" "-Pgradle.publish.secret=${GRADLE_PUBLISH_SECRET}" "-DbuildNumber=${BUILD_NUMBER}" publishPlugins
    - jfrog config import "${JFROG_PROMOTER}"
    - jfrog rt build-promote --status released "${CIRRUS_REPO_NAME}" "${BUILD_NUMBER}" sonarsource-public-releases